server:
  port: 881
spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/idea_bot_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update