package uz.pdp.appideabot.enums;

public enum LangFields {
    BUTTON_LANGUAGE_RU, BUTTON_LANGUAGE_EN, CHOICE_LANGUAGE_TEXT, SUCCESSFULLY_SELECTED_LANGUAGE, JOIN_WITH_CODE_TEXT, MY_PROJECTS_TEXT, BUTTON_LANG_SETTINGS, BUTTON_LANGUAGE_UZ

}
